name: Build VM Disk Image

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches:
      - master

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: ${{ matrix.version }} ${{ matrix.architecture.name }}
    runs-on: ubuntu-latest
    container: ubuntu:23.04
    permissions:
      contents: write
      packages: write
      id-token: write
      deployments: write
    strategy:
        fail-fast: false
        matrix:
          version:
            #- '12.2'
            #- '12.4'
            #- '13.0'
            #- '13.1'
            - '13.2'

          architecture:
            - name: x86-64
              qemu: x86

            #- name: arm64
            #  qemu: aarch64

          exclude:
            - version: '12.2'
              architecture:
                name: arm64
                qemu: aarch64

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          apt update && \
          apt install curl jq unzip \
          "qemu-system-${{ matrix.architecture.qemu }}" -y

      - uses: hashicorp/setup-packer@v2.0.1
        with:
          version: "1.9.1"

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      - name: Install UEFI
        if: matrix.architecture.name == 'arm64'
        run: cp "$(cat /usr/share/qemu/firmware/60-edk2-aarch64.json | jq .mapping.executable.filename -r)" edk2-aarch64-code.fd

      - name: Build Image
        env:
          PACKER_LOG: 1
        run: |
          ./build.sh '${{ matrix.version }}' '${{ matrix.architecture.name }}' \
            -var 'headless=true'

      # - name: Extract Version
      #   id: version
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Upload generated application to the artifacts.
        uses: actions/upload-artifact@v3.1.3
        with:
          name: output
          path: output/*
          retention-days: 1

      # - name: Create Release
      #   id: create_release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     name: FreeBSD ${{ steps.version.outputs.VERSION }}
      #     draft: true
      #     files: output/*

  MakeRelease:
    runs-on: ubuntu-latest
    name: Create release
    needs: build
    permissions:
      contents: write
      packages: write
      id-token: write
      deployments: write

    steps:
      - name: Get output
        uses: actions/download-artifact@v3.0.2
        with:
          name: output

      - name: Extract Version
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: FreeBSD ${{ steps.version.outputs.VERSION }}
          draft: true
          files: output/*